name: Alex Marcy
description: Telling my story through business, music, and technology.
meta_description: "Telling my story through business, music, and technology."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://alexmarcy.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://alexmarcy.com'
author:         'Alex Marcy'
authorTwitter:  'alexmarcy'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
